export { default as Navbar } from './Navbar/index.astro'
export { default as Skills } from './Skills/index.astro'
export { default as About } from './About/index.astro'
export { default as Experience } from './Experience/index.astro'
export { default as ContactMe } from './ContactMe/index.astro'
